title: # Expert Cashew Grafts - Yadukumar Kolathaya 
email: # nyadukumar@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Yashaswi Nursery. Here you can find premium grafts of Cashew, Pepper and Jackfruit, and seedlings of coconut and arecanut.
#  Write an awesome description for your new site here. You can edit this
permalink: ':title/'
baseurl: "/ynursery" # the subpath of your site, e.g. /blog
url: "http://ynursery.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Yashaswi Nursery # add your name
author-pic: yashaswi2.png
about-author: Yashaswi Nursery is located within the lush greens of Western Ghats, about 50 km from the coastal town of Mangalore. It was founded by Dr. N Yadukumar in 2012, a former research scientist of Directorate of Cashew Research (DCR), Puttur.
email: (n yadukumar) at gmail dot com # 
phone: 233758
website: ynursery.com # Add your website, do not add http://
linkedin: ynursery # Add your Linkedin handle
twitter: '@ynursery' # Add your Twitter handle
instagram: ynursery # Add your Instagram handle
pinterest: ynursery # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
# discus_identifier: # mr-brown # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
destination: ./docs/
plugins:
#  - jekyll-paginate
#  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
